server:
  port: 8088

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enables routing to services via service name
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all endpoints, or use comma-separated list like: "health,info"
  endpoint:
    health:
      show-details: "always"  # Options: never, when-authorized, always
    shutdown:
      enabled: true  # Enable shutdown endpoint
  info:
    env:
      enabled: true  # Include env properties in /actuator/info
  server:
    port: 8081  # Optional: Run actuator endpoints on a separate port
