server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/supunsenanayake/microservicestest-config-server.git   #C:\Users\supun\Spring_Test_code\2025\04\06\config-server\config-server\src\main\config-repo
          clone-on-start: true
          default-label: master
          search-paths: src/main/config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
